### ISSUE TITLE
bug?: add ndice失败

### ISSUE THREAD

**Issue by HadalFauna** [HydroRoll-Team/infini#61]
1. 更新python至3.12.3
2. pip install ipdm
3. ipm add ndice 
4. 结果如下

PS C:\Users\Administrator\Downloads\infini-master\infini-master\tests\examples\ndice> ipm add ndice
检查环境中...
环境检查完毕.
处理 Infini 项目依赖锁...
```
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Program Files\Python312\Lib\site-packages\ipm\__main__.py:138 in add                          │
│                                                                                                  │
│   135 ):                                                                                         │
│   136 │   """新增环境依赖"""                                                                     │
│   137 │   try:                                                                                   │
│ > 138 │   │   if api.add(name, index=index, echo=True):                                          │
│   139 │   │   │   tada()                                                                         │
│   140 │   except IpmException as err:                                                            │
│   141 │   │   error(err, echo=True)                                                              │
│                                                                                                  │
│ ┌──── locals ─────┐                                                                              │
│ │ index = None    │                                                                              │
│ │  name = 'ndice' │                                                                              │
│ └─────────────────┘                                                                              │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\ipm\api.py:377 in add                               │
│                                                                                                  │
│   374 │   │   ...                                                                                │
│   375 │                                                                                          │
│   376 │   info("处理 Infini 项目依赖锁...", echo)                                                │
│ > 377 │   ipk.add(name, version, dump=True)                                                      │
│   378 │   lock.add(name, version, dump=True)                                                     │
│   379 │   success("环境依赖新增完成.", echo)                                                     │
│   380                                                                                            │
│                                                                                                  │
│ ┌────────────────────────────────── locals ──────────────────────────────────┐                   │
│ │         echo = True                                                        │                   │
│ │        index = None                                                        │                   │
│ │          ipk = <ipm.models.ipk.InfiniProject object at 0x00000220BE421850> │                   │
│ │         lock = <ipm.models.lock.ProjectLock object at 0x00000220BB5E43E0>  │                   │
│ │         name = 'ndice'                                                     │                   │
│ │     pkg_lock = <ipm.models.lock.PackageLock object at 0x00000220BD828650>  │                   │
│ │ splited_name = ['ndice']                                                   │                   │
│ │      version = None                                                        │                   │
│ └────────────────────────────────────────────────────────────────────────────┘                   │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\ipm\models\ipk.py:125 in add                        │
│                                                                                                  │
│   122 │   │   │   │   self.dependencies.remove(dependency)                                       │
│   123 │   │   │   │   break                                                                      │
│   124 │   │                                                                                      │
│ > 125 │   │   self.dependencies.append(                                                          │
│   126 │   │   │   {                                                                              │
│   127 │   │   │   │   "name": name,                                                              │
│   128 │   │   │   │   "version": version,                                                        │
│                                                                                                  │
│ ┌─────────────────────────────── locals ────────────────────────────────┐                        │
│ │    dump = True                                                        │                        │
│ │    name = 'ndice'                                                     │                        │
│ │    self = <ipm.models.ipk.InfiniProject object at 0x00000220BE421850> │                        │
│ │ version = None                                                        │                        │
│ └───────────────────────────────────────────────────────────────────────┘                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'dict' object has no attribute 'append'

```

以及直接从仓库拉取infini主分支后，python tests.py显示导入缺乏模块multilogging
```
<string>:66: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "E:\dice\iamai\iamaiTestBot\infini-master\tests\examples\ndice\tests.py", line 12, in <module>
    loader.load("ndice")
  File "C:\Program Files\Python312\Lib\site-packages\infini\loader.py", line 139, in load
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Program Files\Python312\Lib\site-packages\infini\loader.py", line 82, in exec_module
    exec(Path(self.filename).read_text("utf-8"), vars(module))
  File "<string>", line 8, in <module>
  File "C:\Users\Administrator\.ipm\src\ndice\src\dicer.py", line 1, in <module>
    from multilogging import multilogger
ModuleNotFoundError: No module named 'multilogging'
```

**Comment by HsiangNianian** [comment]
针对库缺失问题可以安装依赖: `multilogging`

**Comment by fu050409** [comment]
针对第一个问题，这是由于你在`ndice`规则包中试图添加它自己，这是一个非法操作，我会在稍后进行更新针对性的异常处理。

第二个问题是由于 @HsiangNianian 尚未完成世界树功能，手动部署的`ndice`规则包不是最新版，`multilogging`依赖尚未被移除，这需要等待上游处理。

**Comment by HsiangNianian** [comment]
## Q1

请等待适配 @fu050409 设计的世界树镜像。

## Q2

请先激活 *pdm* 环境，随后使用 `pdm run` 命令运行 *ndice/tests.py*
